# Generated by Django 5.0.1 on 2024-02-20 19:47

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import gdstorage.storage
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=44)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to=main.models.UniqueFileName('profile_pics'))),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('country', django_countries.fields.CountryField(default='PL', max_length=2)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_founder', to=settings.AUTH_USER_MODEL)),
                ('key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_key', to='main.key')),
            ],
            options={
                'permissions': [('add_new_member', 'Can add new team memeber'), ('delete_member', 'Can delete team memeber'), ('manage_perms', 'Can manage all permission in team')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to=main.models.upload_to_team_folder, validators=[main.models.CustomFileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.SmallIntegerField(default=1)),
                ('privacy_level', models.CharField(choices=[('public', 'Publiczny'), ('confidencial', 'Poufny'), ('secret', 'Tajny')], default='public', max_length=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_files', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'permissions': [('view_confidencial', 'Can view confidencial files'), ('edit_confidencial', 'Can edit confidencial files'), ('download_confidencial', 'Can download confidencial files'), ('view_secret', 'Can view secret files'), ('edit_secret', 'Can edit secret files'), ('download_secret', 'Can download secret files')],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_member', through='main.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
