# Generated by Django 5.0.1 on 2024-02-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': [('download_file', 'Can download file'), ('view_confidencial', 'Can view confidencial files'), ('edit_confidencial', 'Can edit confidencial files'), ('download_confidencial', 'Can download confidencial files'), ('view_secret', 'Can view secret files'), ('edit_secret', 'Can edit secret files'), ('download_secret', 'Can download secret files')]},
        ),
    ]
