# Generated by Django 5.0.1 on 2024-01-21 16:55

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=main.models.UniqueFileName('profile_pics')),
        ),
    ]
