# Generated by Django 5.0.1 on 2024-03-11 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_file_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.teammembership')),
            ],
        ),
    ]
