# Generated by Django 5.0.1 on 2024-03-11 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teammessage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammessage',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
            preserve_default=False,
        ),
    ]
