# Generated by Django 5.0.1 on 2024-03-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teamactivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('add_new_member', 'Can add new team memeber'), ('delete_member', 'Can delete team memeber'), ('manage_perms', 'Can manage all permission in team'), ('view_logs', 'Can see team logs')]},
        ),
    ]
