# Generated by Django 5.0.1 on 2024-03-25 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_last_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
