# Generated by Django 5.0.1 on 2024-01-24 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_name_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
