# Generated by Django 5.0.1 on 2024-01-24 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='team_files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
