# Generated by Django 5.0.1 on 2024-01-26 16:51

import gdstorage.storage
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to=main.models.upload_to_team_folder, validators=[main.models.CustomFileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
