# Generated by Django 5.0.1 on 2024-01-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_key_team_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='key',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='team',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_key', to='main.key'),
        ),
    ]
