# Generated by Django 5.0.1 on 2024-01-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_key_key_value_alter_team_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_key', to='main.key'),
        ),
    ]
