# Generated by Django 5.0.1 on 2024-02-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_team_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='varsion',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
