# Generated by Django 5.0.1 on 2024-02-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_file_varsion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='varsion',
            new_name='version',
        ),
    ]
