# Generated by Django 5.0.1 on 2024-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_varsion_file_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.SmallIntegerField(default=1),
        ),
    ]
